root = "."
tmp_dir = "tmp"

[build]
  # 指定构建命令，使用 /cmd/miniblog/main.go
  cmd = "go build -o ./tmp/main ."
  # 指定二进制文件路径
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "build"]
  include_dir = []
  exclude_file = []
  delay = 1000
  stop_on_error = true
  log = "build-errors.log"

[watch]
  dir = "."
  include = ["*.go"]
  exclude = []
  delay = "100ms"

[log]
  time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true