root = "."
tmp_dir = "_output"

[build]
  # 指定构建命令，使用 /cmd/miniblog/main.go
  cmd = "go build -o ./_output/main ./cmd/miniblog/main.go"
  # 指定二进制文件路径
  bin = "./_output/main"
  include = ["*.go"]
  exclude = ["web/**/*"]
  exclude_dir = ["web", "tmp", "_output", "node_modules", "dist"]

[watch]
  dir = "."
  include = ["*.go"]
  exclude = ["web/**/*"]
  exclude_dir = ["web", "tmp", "_output", "node_modules", "dist"]
  delay = "100ms"

[log]
  time = true
  color = true