app:
  name: "blog-serve"
  version: "1.0.0"
  mode: "development"  # development, production

# 服务器配置
server:
  name: "blog-serve"
  address: "0.0.0.0"
  port: 8080
  read_timeout: 60    # 秒
  write_timeout: 60   # 秒

# 数据库配置
database:
  driver: "mysql"
  host: "47.94.204.124"       # 使用 docker-compose 中的服务名
  port: 13306
  username: "www"
  password: "Hm6EB6Q!y2xT5T"
  dbname: "blog_db"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # 秒

# redis 配置
redis:
  host: "47.94.204.124"      # 使用 docker-compose 中的服务名
  port: 16379
  password: "T2XFVfU3DCenEnL"       # 如果没有密码则留空
  db: 0
  pool_size: 100
  min_idle_conns: 10

# 日志配置
log:
  level: "debug"     # debug, info, warn, error
  filename: "logs/app.log"
  max_size: 100      # MB
  max_age: 30        # 天
  max_backups: 7
  compress: true

# jwt 配置
jwt:
  secret: "45df45rds4"
  expire: 86400      # token 过期时间（秒）

# cors 配置
cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"