app:
  name: "miniblog"
  version: "1.0.0"
  mode: "development"  # development, production

# 服务器配置
server:
  name: "miniblog"
  address: "0.0.0.0"
  port: 8081
  read_timeout: 60    # 秒
  write_timeout: 60   # 秒

# 通用配置
runmode: debug               # Gin 开发模式, 可选值有：debug, release, test
addr: :8081                  # HTTP 服务器监听地址

# 数据库配置
database:
  driver: "mysql"
  host: "mysql"
  port: 3306
  username: "miniblog"
  password: "miniblog123"
  dbname: "miniblog"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # 秒
  log_level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# redis 配置
redis:
  host: "redis"      # 使用 docker-compose 中的服务名
  port: 6379
  password: ""       # 如果没有密码则留空
  db: 0
  pool_size: 100
  min_idle_conns: 10

# 日志配置
log:
  disable-caller: true # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-stacktrace: true # 是否禁止在 panic 及以上级别打印堆栈信息
  level: debug # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  format: console # 指定日志显示格式，可选值：console, json
  output-paths: [/data/logs/miniblog/miniblog.log, stdout] # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输出，

# jwt 配置
jwt:
  secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5 # JWT 签发密钥
  expire: 86400      # token 过期时间（秒）

# cors 配置
cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"

# HTTPS 服务器相关配置
tls:
  addr: :8443 # HTTPS 服务器监听地址
  cert: ./_output/cert/server.crt # 服务端证书文件
  key: ./_output/cert/server.key # 服务端私钥文件